### PR TITLE
application design EAP (early access preview)

### LINKED ISSUE #4: Application Design for Desktop
## Type of Change
- [x] New Documentation
- [x] Update to existing documentation
- [x] Other (please clarify below)

## Summary

An Application Design is helpful for establishing the basic features, users stories, and look and feel of the project.  
1.  Overview
1.  Pages
1.  Components
1.  Services

The application design should have screens and images and link out to more technical documentation where appropriate.

## Related Issues
Mobile Design will be updated by 10/27 on #26

### PR DESCRIPTION
**Pull request by thescientist13**
## Related Issue

resolves #4 

## Summary of Changes

[Application Design](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design) is mostly there, still needs
1. [x] images for each page and component
1. [x] contact information 
1. [x] header capabilities

### CODE REVIEW

**Review by kpisano — APPROVED** [review]

**Review by saimatsumoto — APPROVED** [review]

**Comment by saimatsumoto** [comment]
Working toward completion by 10/27.

**Comment by saimatsumoto** [comment]
- [x] Requirements updated for: 
    * Header
    * Footer
    * Hero Banner
    * Navigation Bar
    * Events List 
    * Blog Posts
    * Blog Details page
- [x] images for each page and component by 10/26.

**Comment by thescientist13** [comment]
@saimatsumoto 
This needs a merge conflict to be resolved before it can be merged.  Let me know if you need any help with rebasing your branch from master.

**Comment by saimatsumoto** [comment]
@thescientist13 conflict resolved.

**Pull request merged**
